### PR TITLE
move list of groups to a sidebar

### PR DESCRIPTION
**Pull request by brortao**
this is to make room for a forthcoming "polls" tab at the bottom.

this PR also sets a `currentGroupId` in the local state. this means that we don't have to pass around the group ID in the navigation parameters -- we were doing this before and it was quite messy!

### CODE REVIEW

**Comment by wobbly-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please add an entry to the changelog.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Changed Files in this PR: 
- .gitignore
- .loki/reference/iphone7_screens_ThreadsListScreen_Standard.png
- apollo.config.js
- assets/icon.png
- assets/splash.png
- src/App.tsx
- src/AppNavigation.tsx
- src/apolloClient.ts
- src/components/molecules/NonIdealState.tsx
- src/components/organisms/ErrorState.tsx
- src/components/organisms/LoadingState.tsx
- src/components/organisms/ThreadsList.tsx
- src/components/organisms/index.tsx
- src/components/screens/AccountScreen.tsx
- src/components/screens/CreateThreadScreen.tsx
- src/components/screens/EditGroupDescriptionModal.tsx
- src/components/screens/EditGroupNameModal.tsx
- src/components/screens/GroupDetailsScreen.tsx
- src/components/screens/SplashScreen.tsx
- src/components/screens/ThreadsListScreen.tsx
- src/graphql/README.md
- src/graphql/queries/queries.ts
- src/graphql/queries/types.ts
- src/services/NavigationService.ts
- src/util.ts
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6a720b47f7a4925dcdc7bbc237bd270d7e0d7f83
</p>

**Comment by brortao** [comment]
@chrisdevereux do you have the bandwidth to chat about testing anytime soon?

i've made some changes to how things work here that affect tests. for instance, molecule or organism components may now query the backend. as far as i can tell, the tests are set up such that only screen components get mocked graphql responses.

**Comment by brortao** [comment]
ah, the above problem was pretty easy to resolve, but i'm now running into something else.

the new component `DrawerNav` lists the groups that you're a member of. for some reason, it's getting the same group twice:

Screenshot from 2019-06-24 20-08-27

i'm not quite sure where to modify the mocked graphql responses, so not sure where to statr debugging!

**Comment by chrisdevereux** [comment]
Hey @brortao, hope you're good!

The reason that this was happening is that there `Query.groups` wasn't mocked. If you don't mock a property, then Apollo infers what to do based on the type (in the case of a list, it calls the mock specified for the type twice).

Our test data generators are deterministic, so unless they get a numeric parameter specifying which example to use, they will always return the same thing.

Providing an explicit implementation for `Query.groups` fixes this. I just pushed a commit showing how to do this. And fixed a couple of other things around mocking API requests that I spotted while I was in there...

**Comment by brortao** [comment]
thank you @chrisdevereux! that's very helpful -- the mocking is starting to make sense now. i appreciate that you took the time to help while you're busy! :)

**Pull request merged**
