### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by KieranPringle**
Surprisingly, this is apparently enough config to add Travis to the project according to their documentation. Since the project uses default yarn commands and a standard structure, Travis will apparently automatically use yarn to install and automatically run `yarn test`. 

Have tested the series of commands that Travis will run and they all work for me locally except from the tests. The only existing test fails for me locally. Expect it will do the same on Travis. Not sure how to fix it.

I don't have owner permission on this repo so can't set Travis up but if someone else who does gets it added to this repo then it should start building this pr automatically and I can do a bit more testing.

### CODE REVIEW

**Comment by apodiptych** [comment]
It looks like travis is using an old node version -- do you know if it's possible to use something more recent?

**Comment by KieranPringle** [comment]
@apodiptych I've updated to version 10, this seems to get rid of the warnings. There is a failing test, though this is handled in this PR by @marcaaron: https://github.com/Wobbly-App/wobbly-frontend/pull/22

**Comment by marcaaron** [comment]
Does this branch solve a different issue from @nam20485's docker set up? I noticed there was a `travis.yml` file over here too --> #20

**Comment by nam20485** [comment]
> Does this branch solve a different issue from @nam20485's docker set up? I noticed there was a travis.yml file over here too --> #20

I don't think it solves a separate issue. They solve the same issue in that they both add a travis.yml config file that enables the travis build of this repo. His stops there though, while mine adds much more functionality beyond that. Mine is the implementation of  the "Dockerize frontend issue": https://github.com/Wobbly-App/wobbly-frontend/issues/3 and the Create deployment pipeline issue: https://github.com/Wobbly-App/wobbly-backend/issues/6. I told everyone I was working on them in the sprint review and had everything almost working, so I am not sure why he is also working on that. Maybe a mis-communication since he didn't come to the sprint review.

They are not strictly compatible in that his travis build specifies a node_js build, which I have changed in mine to run the a Docker build. Since we want to have the travis pipeline build the docker container, I have switched the travis configuration from building it as node_js to building the docker container.

My branch adds much more functionality beyond that initial step: 

- building the docker container
- unit testing
- beginning of deployment to google cloud

Since mine has much more functionality and has progressed far beyond the basic travis setup here, we have two options, merge his in and then merge mine on top, or not merge this and just merge mine.

**Pull request closed without merging**
