### PR TITLE
Add account screen

### LINKED ISSUE #7: Editing your Profile Page, avatar, email, password

### PR DESCRIPTION
**Pull request by apodiptych**
Fixes #7.

To do:

* [ ] ~Handle request/success/failure state in the component instead of redux store?~
* [x] Write reducer for response
* [x] Fix `ActivityIndicator` spinning forever

### CODE REVIEW

**Comment by marcaaron** [comment]
⚠️ strongly in favor of utilizing component level state over redux whenever possible!

**Comment by apodiptych** [comment]
@marcaaron yeah, I agree. the reasoning here is that a user can make some account changes, submit the form, and then navigate away from the screen (thus unmounting it). when they return to the account screen they should still see the state of their request.

**Comment by apodiptych** [comment]
Should be ready to go. I'm reluctant to add more detail (e.g. proper password changes, avatar support) until we get a backend in place but now the framework is there!

**Comment by marcaaron** [comment]
Looks good!

**Pull request merged**
