### PR TITLE
Use graphql schema from staging server rather than apollo engine

### PR DESCRIPTION
**Pull request by chrisdevereux**
This replaces the source schema used to generate graphql interface types, moving from Prisma's schema repository to our current staging server.

It means that developers don't need an API key to generate interface types and allows CI to run on forked branches.

The other effect of this is that CI will fail if front-end interface types aren't kept up to date with staging... which appears to be the case now. So we need the following merged into the front-end repository before this can be merged:

````
.../src/graphql/mutations/mutations.ts: Cannot query field "updateGroup" on type "Mutation". Did you mean "createGroup", "leaveGroup", or "updatePerson"?
.../src/graphql/mutations/mutations.ts: Cannot query field "memberCount" on type "Group". Did you mean "members"?
.../src/graphql/mutations/mutations.ts: Cannot query field "toggleThreadPinning" on type "Mutation".
.../src/graphql/mutations/mutations.ts: Cannot query field "confirmEmail" on type "Mutation".
.../src/graphql/queries/queries.ts: Cannot query field "emailConfirmed" on type "Person".
.../src/graphql/queries/queries.ts: Cannot query field "memberCount" on type "Group". Did you mean "members"?
.../wobbly-frontend/src/graphql/fragments.ts: Cannot query field "pinned" on type "Thread".
````

### CODE REVIEW

**Comment by brortao** [comment]
ah perfect, thank you!
i'll deploy the required changes to the backend.

but first -- should we perhaps just have a stack that deploys from `develop`? things are moving pretty fast at this stage of the project so while we're in alpha that may be acceptable. what do you think?

**Comment by chrisdevereux** [comment]
You mean, like setting up the Heroku staging server to auto-deploy from develop? Yeah, I think that's alright at this point. Once things stabilise, we could always change our approach...

**Comment by brortao** [comment]
@chrisdevereux the build is now passing. this helped uncover several issues with our backend infrastructure, so thank you! feel free to merge when you see fit :)

**Comment by chrisdevereux** [comment]
@brortao one of the travis status checks seems to be stuck its status. could you admin-merge it, seeing as the build did actually pass?

**Pull request merged**
